services:
  - type: web
    name: flights-by-country
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: FLIGHT_API_KEY
        sync: false
      - key: CACHE_TTL
        value: 300
      - key: CACHE_MAXSIZE
        value: 100
      - key: RATE_LIMIT
        value: "30/minute" 